### ISSUE TITLE
Wrong project section

### ISSUE THREAD

**Issue by berkil** [Rommmmm/gcloud-connect#2]
The python script shows the projects name column instead of the project-id column, 
Due to that- it's not possible for me and maybe for other users to connect to the servers.

The exception i'm getting is:

 `ERROR: (gcloud.compute.instances.list) Some requests did not succeed:
  \- Invalid value for project: boris-project`

**Comment by Rommmmm** [comment]
You are right sir!
the project-id and the project-name in the environment that i had tested this script on were probably the same.
I will change the column to the right one tomorrow

Thank you for your sharp eye.
