### ISSUE TITLE
Deletion improvement 

### ISSUE THREAD

**Issue by berkil** [Rommmmm/gcloud-connect#3]
When the code exits, you have to delete some temp files, to make it simple- you can write all the temp file into /tmp/google-connect/ 
and when the user choose option `[0]` to exit, you will call a function which will delete the entire folder

Because now the script writes the files to /tmp and to the working directory, and its not deleting always the files, even befor this commit #1

**Comment by Rommmmm** [comment]
are you talking about sh or py script?

**Comment by berkil** [comment]
The bash script

**Comment by Rommmmm** [comment]
just committed a new one check if it fixed, from my attempts it deletes everything

**Comment by berkil** [comment]
Works great!
